#if !canImport(ObjectiveC)
import XCTest

extension GPXExporterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GPXExporterTests = [
        ("testExportingACompleteTrack", testExportingACompleteTrack),
        ("testExportingAnEmptyTrackWithDateAndTitleResultsInAnEmptyGPXFile", testExportingAnEmptyTrackWithDateAndTitleResultsInAnEmptyGPXFile),
        ("testExportingAnEmptyTrackWithoutDateResultsInAnEmptyGPXFileWithoutTitleAndDate", testExportingAnEmptyTrackWithoutDateResultsInAnEmptyGPXFileWithoutTitleAndDate),
        ("testExportingANonEmptyTrack", testExportingANonEmptyTrack),
        ("testItWillNotExportTheDatesFromTrack", testItWillNotExportTheDatesFromTrack),
    ]
}

extension GPXParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GPXParserTests = [
        ("testImportingAnEmptyGPXString", testImportingAnEmptyGPXString),
        ("testParsingGPXFilesWithoutATrack", testParsingGPXFilesWithoutATrack),
        ("testParsingTrackSegmentsWithExtensions", testParsingTrackSegmentsWithExtensions),
        ("testParsingTrackSegmentsWithoutExtensions", testParsingTrackSegmentsWithoutExtensions),
        ("testParsingTrackSegmentsWithoutTimeHaveANilDate", testParsingTrackSegmentsWithoutTimeHaveANilDate),
        ("testParsingTrackTitles", testParsingTrackTitles),
        ("testTrackLength", testTrackLength),
    ]
}

extension TrackGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TrackGraphTests = [
        ("testCLCoordinates2D", testCLCoordinates2D),
        ("testElevationGainIsTheSumOfAllElevationDifferences", testElevationGainIsTheSumOfAllElevationDifferences),
        ("testInitializationFromGPX", testInitializationFromGPX),
        ("testSegmentDistances", testSegmentDistances),
        ("testTheInitialElevationIsSubstractedFromTheElevationGain", testTheInitialElevationIsSubstractedFromTheElevationGain),
        ("testTotalDistance", testTotalDistance),
        ("testTotalElevationWithDifferentElevation", testTotalElevationWithDifferentElevation),
        ("testTotalElevationWithTheSameElevationAtEveryPoint", testTotalElevationWithTheSameElevationAtEveryPoint),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GPXExporterTests.__allTests__GPXExporterTests),
        testCase(GPXParserTests.__allTests__GPXParserTests),
        testCase(TrackGraphTests.__allTests__TrackGraphTests),
    ]
}
#endif
